theme: jekyll-theme-slate

title                    : "From universe"
name                     : "Quasar"
description              : "Study note"
url                      : "https://quasar-anderson.github.io/website"
baseurl                  : # 서브 경로가 있는 경우 기재
